---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - serviceaccount.yml
  - clusterrole.yml
  - secret.sops.yaml
  - configmap.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pvc.yml