apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-data
  namespace: myapps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi