apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: network
  labels:
    app: homepage
  annotations:
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: homepage