apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
  namespace: myapps
  labels:
    app: homepage
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: homepage
