---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.15.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      replicas: 1
    node:
      tolerateAllTaints: true