apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi
  volumeName: minio-nfs-pv
