apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: http://192.168.0.123
  share: /HOMELAB/k8sNFS/
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - head
  - nfsvers=4.1
