---
originRequest:
  noTLSVerify: true

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc http://external-ingress-nginx-controller.network.svc.cluster.local:80
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - service: http_status:404
