---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway.observability:80
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
          derivedFields:
            - name: "TraceID"
              matcherRegex: "trace_id=(\\w+)"
              url: "${__value.raw}"
        editable: true