---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
type: Opaque
stringData:
  admin-user: admin
  admin-password: "Adminnk7E$M7#YJfG5v"  # You can change this password