# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:QP8KBuje72MbELQ1Dg27S+/myKD/76srTemPCYJANAxuYs+BU7Vlb2TZbgQbdeH8eIAIqlwe+ruCeetWZwBwcWlp0MnwBeCcC+KR06vF+BNVtjRMTkWmjGImaSos0hAxi4HBsg3LW1mVw7nzlB11+rsof3EaGTp1peXaVauII7f0hcezBJdilmX+L3/PdoQErJOuFk/U7Aq6eRpP0DDCAS6Zm/gToTEL5BKpIWdLfQqtW3+nTA==,iv:iPleKhA+uK+bRkPd+ogp/45OSkFnmUQc/lhPraYhWRw=,tag:xiMR6BFG4nkCILJ4EBHBMQ==,type:str]
sops:
  age:
    - recipient: age1r2etnyxjn5wm2ycwf8wv5ntmvtj7dl2ppqae2y0laf6tptyenu8sustqgj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QktDZ05jMnVrYXRpNjZN
        T3FiR1VQTVNaejNaZFJ1MGlqcnZTUlRialRFCklKc01nRmloS1NKVVdsZjBDV2hM
        QnhKdlQxb2ZXTGlpNzVyRGNNNFhzVFEKLS0tIHU0VStrek1NY0xLZVp5RHoyeDBN
        ck9YMTBrSnVxTE5YZUhmRThZNkxuaHcKktvHJZLglWd2zx9yhalVZz83Z8qav3m0
        uM0L+2pDrP7Lq4to/L+sp1W7bd22YtYAuO+HVOyWfvuIivAoDdkoPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-25T04:59:03Z"
  mac: ENC[AES256_GCM,data:2Ofq+pkAo7gOdHZbrgO5K/EqkeykpnFcyR+XcNxk1av8g9VFyZLVNx4Usp28FkRaQ2FsLV8dHsB1/fMuOvf3rgcMP2BBd/wqUINPXwD/3f1BmHKA/Qhtsyz0YKqDRrpOcBu50VbPkzjCATD+CGJq4L7nAggn+DGzv4mEJfoFLk8=,iv:DRj67BIaB4Zv+6QfUAkPRx9Yr3sVJAphMV/81qH7ZkE=,tag:YAmYM5zqS7Nz1tD0ElyI2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
