apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hTLVMzw2awRnNI+pSj9BoNpEfijbli5/itw7Dl2XDUeD16/H,iv:+BlibKlOOOCIXDoDdnyiO4dRi2JWqGHYUVy2GnQv3DA=,tag:+X5EpLJWquLHGwF4Iwi92A==,type:str]
    credentials.json: ENC[AES256_GCM,data:SsEcvVDX0LBfPPe09hcrswKCkPqrEROGFGIMEGtUQH+7b4T+D6YfP667loh1l4BPLKuhCMiuFR8vAc+9v2WbOEjqa5aw72t9WFFdNdSCdk1YeG3VSQ2DL5MVHfgMzxfhQK4f0ClyIeDkSEtDqYUVgCaWrF1GmfroGmqua8hRLhrMYAOZk1k36xACGlHqdHNn1Tpb5VpgkTPL5biTITRaE2l/6q4sPHNhJNkTvwpGwQ==,iv:Lt0MfcoSUmsAa7MCBrgXNUl/ZnsZDOzKDDSngtjTZ6w=,tag:dffSpHV5y0/4LIaG2MbL4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lcg2c8efnnnmmlq5ftp85v8enwc7adhrm4auqnjfckww76fj6vrs5redm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL3JUMjJVdU84WFZiSWVo
            K1MyaEpkdEdSMzBuOUdKanlRMkdxRGVSVTBJCkZIaWlxYXk5SXBTMU10K2diZml3
            azU0NkNSanN0WWZ0RkRSUFpLazJFbHcKLS0tIHE1aWR6SmVMOEM4akc3NW5Sb21Z
            czhqODdidkZ5MEk2S3RETEhCcjJlMEkKdP3/Z8tNEDL1U8FxZo67cF/riTJB+Hte
            dqHo/icpyb7bdgiM06+9xcE+Af5a5KQ/xqFTOHUZo7z58rHt+Vmphw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T04:32:11Z"
    mac: ENC[AES256_GCM,data:pWsg4mqER75Y1rVlB56QQWY/gNGkR2vrbJ4O81n/uEaosTpTpeeFAql7v2Ez1Dt9QmqN4BMW3xn3aVlS3qKS1rKz81K7It1MgN6/T27Nn2k2ns1rXd0/XsYMOV8rmCwO4SfCIh5K5EpZ1lbWyDB0C/K7Ajnq5J85fc0jXlFxYRk=,iv:i8+YfGWukKKQ/p6YEcDTPEZ2TRspS43/DfZgIJvE+/8=,tag:z+LnCyAg5zp0uGzUdQ5UVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
