apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:gbJKGlTwgpE9abu0rFrN5AhJcLVHrfjk7CXcn4LBDvnSRoNQ,iv:6UmY61XMUDvo5JiKST7NQnoTIi1GyUtTjYRLfG0zC6M=,tag:OYkZrExR112cd927Bxj8yg==,type:str]
    credentials.json: ENC[AES256_GCM,data:ruKzHPsDb34EtVhFRuk1jiwZUqY0aChw3+UerdUmEmAKBMnWcBpOv+X1qDRmK4qIoouO05WaCYqURAZ37BqLDXcFmx7Oa/Mz73YzbNZ6yvBC+yrQTW607/JjDL3aHjmpB66QPI+JHyGReF6jxT05HzRcWoNXPm9TUIKKK2zKMlR+fTZPBqdnDVAIwx11szaWoFZBnnwxToqxcDfaCfUSFzTMJqGBmqFFM2V997BYBw==,iv:HORmiaYJM16sEySNKaV9ZOxHTPW0fylTXE96qZA8TOU=,tag:nD6nuqAAfC361xVCFrbvqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lcg2c8efnnnmmlq5ftp85v8enwc7adhrm4auqnjfckww76fj6vrs5redm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZDgrbkhuNjFJRURvYVli
            NHJFcXFpbjVFcFZHdFJGcTNZY2luMUNGWXdZCjliVW91R0IrMzlpTW45Z3RFTzZF
            aXkzTjE0M05CQ0pub3hSbkFqWFBsV28KLS0tIFp1a051YnZRa3dES3E5Z3pKK3lH
            RmNqTUNwTDR3dHExRFJQTGJmZVJQVlEK1g23J5lvMgtXFwBLryt4SZafumraOFbR
            awwcSG2gp3ZqN5x6uuir6VFj3qe8tE5J4Is55L2ThAMSSTxy6d3zqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T18:20:11Z"
    mac: ENC[AES256_GCM,data:y8RcKPr4FFmpV3HzpnSfHgeevvqVKuZTkBXsiiNgq8zhlpZQlQAeON8k1ycPHbmPtmWbMK6PdKUuKOsbH1xQ/eQcqe/AXE3wQ/TWSFD51DMdbQUOuI1COd6i3QG6sKivpr1VXRLaIHGMIYrH3ElARnEFLulwSCZBrMhQWDMmNOk=,iv:VJ+L9lDuC8K3qwp3q9qaflMf1CyxO5C03DbkoHaCqP8=,tag:KyQt1UjmY6C5XvsOW2k89w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
