apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  generation: 2
  name: on-call
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
  - kind: HelmRepository
    name: podinfo
  - kind: HelmChart
    name: default-podinfo
  - kind: HelmRelease
    name: '*'
    namespace: default
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
