# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fWIJ+JGAzFeWfJxjWC05p+dot6HGUlX5VlL4Y6xdFNk=,iv:/ePdAWI2nim/rdinzXAt+X1mbgGVhX3DdQSwbEorJ/w=,tag:3JKk6mNYPYDOm+zuuDjFDQ==,type:str]
sops:
  age:
    - recipient: age1r2etnyxjn5wm2ycwf8wv5ntmvtj7dl2ppqae2y0laf6tptyenu8sustqgj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTTFDbk9CS21OSnZmWDN6
        QjNJS3pqTDBvVUpDV3dhalNMQWdkbmhzaVVvCkpFRlNkRExQYjlaUEN3SEVvZEhH
        S1o3NG5aN0h4eUhGc1E2cVBpdXRYZUkKLS0tIGR1NW4rU3hiWFZDdE01dTRvQ2ZD
        R1hQdW9ZTStSSWRGejY1WUVNQVVMNTAK9n47IXUuIVQaNFtUxynPcjJ7C7HlOQyp
        GsGhDJ5k6ziuzIyOAUbtNSjYU2/ZIbVIc66yZS+Eumljx00tbeqQwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-22T05:02:41Z"
  mac: ENC[AES256_GCM,data:y3zuBO+8BMVYRaH+iTnjwXwIqIF2VvIt0vrs+jwt1llZCCoEGngvrtUTXk69z6DVYpTkw0Yh9ttqxlAFqOxpWTvNMOBFLvrvUhFfk+9t4zAHF1Pq+cYJS/9fFcZ5wjnEJVbX7aZoXJ8HN4TwyknFnsTRh/tULeSJWnXV+2HF6ZY=,iv:igTSbBhdclG1pgx76riyrMfLQP8E3V2fhSkKANYz33U=,tag:nYPL32+LdS2GPa+UmBgJXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
