# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pzUSkQjYFioBKUEDk0VsevOf9xSJj0OzSRWnxMS6GQg=,iv:W3WQbDc6x64tsL8dkv4B5soNRGJXiJLRXrMQtxQPMOw=,tag:T49zlU5U1fNljuqKXdywTQ==,type:str]
sops:
  age:
    - recipient: age1r2etnyxjn5wm2ycwf8wv5ntmvtj7dl2ppqae2y0laf6tptyenu8sustqgj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZm5sVWgvR0F0N0l4L1o5
        TStwWW85QVhCT0NmTms3T0xEdjRULzFhblhjCm5hakZkYVQvbG11TlZjS3UvT2hz
        SmtpNjltSDJKSXZnajFqVXJ1TDg3TlEKLS0tIGUrOSszYVVpWU9ldWJrMWdzaC8v
        SjE1a1A1N2xzanVjTGtrRlM4U2NMb3MKqOmsEcyyYD4RiRvNvNicMperKvC7jFHC
        MuZeapNySGeziVh+eXnIMKsS8NKEuuehRvkXed5popI4jKgOAud87Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-25T04:59:02Z"
  mac: ENC[AES256_GCM,data:DsF/TM/2g7aSECawwcF/OwrJUeJ1lYHVC/8NhJfyFhEgrUgKOGYiXeQFavjQPBp5MmPqpXiZzgjhZy/RRFoJPYy1JaG2b66USbRygEQuVLnbPGcCFbz19D6DLvQVOqIL/2WevHa8J7WXdHZKRHX9bgO8bGwtZEhMaILvi7rUisM=,iv:35PFeix74fyXaNBkw9PpXrYoypwQ1uNzrjI999PQTOY=,tag:MR1AdtN0sBcsf69OuBJbmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
