---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Ensure all resources are created in the correct namespace
    namespaceOverride: "longhorn-system"

    # Persistence settings
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
      migratable: false

    # CSI settings
    csi:
      kubeletRootDir: /var/lib/kubelet
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1

    # UI settings
    ui:
      replicas: 1

    # Manager settings
    manager:
      priorityClass: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    # Driver settings
    driver:
      priorityClass: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    # Default settings for new volumes
    defaultSettings:
      defaultReplicaCount: 1
      defaultDataPath: /var/lib/longhorn/
      defaultLonghornStaticStorageClass: longhorn-static
      backupstorePollInterval: 300
      failedBackupTTL: 1440
      restoreVolumeRecurringJobs: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 15
      upgradeChecker: false
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort

    # Ingress for UI
    ingress:
      enabled: false