---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Longhorn'
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - longhorn.home.samboxlab.top
      secretName: longhorn-home-samboxlab-top-tls
  rules:
    - host: longhorn.home.samboxlab.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: longhorn-system
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkSDY1dnlzWjgkaE5WQ2pPa1lhVmJUM0lZZWtFTVJWLw==  # admin:longhorn