---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      immich:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.121.0
            env:
              IMMICH_WEB_URL: https://immich.samboxlab.top
              IMMICH_SERVER_URL: https://immich.samboxlab.top
              DB_HOSTNAME: immich-postgresql
              DB_DATABASE_NAME: immich
              DB_USERNAME: immich
              DB_PASSWORD: 7jN!CeA##pySi5  # Change this password
              REDIS_HOSTNAME: immich-redis
              LOG_LEVEL: info
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 2Gi
          machine-learning:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.121.0
            env:
              IMMICH_WEB_URL: https://immich.samboxlab.top
              IMMICH_SERVER_URL: https://immich.samboxlab.top
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 2Gi

    service:
      app:
        controller: immich
        ports:
          http:
            port: 3001

    ingress:
      app:
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        hosts:
          - host: immich.samboxlab.top
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - immich.samboxlab.top
            secretName: immich-tls

    persistence:
      library:
        type: persistentVolumeClaim
        storageClass: nfs
        accessMode: ReadWriteMany
        size: 500Gi
        globalMounts:
          - path: /usr/src/app/upload
      thumbs:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 50Gi
        globalMounts:
          - path: /usr/src/app/upload/thumbs
      profile:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /usr/src/app/upload/profile