---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-postgresql
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      postgresql:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/tensorchord/pgvecto-rs
              tag: pg14-v0.2.0
            env:
              POSTGRES_DB: immich
              POSTGRES_USER: immich
              POSTGRES_PASSWORD: 7jN!CeA##pySi5  # Change this password
              POSTGRES_INITDB_ARGS: "--data-checksums"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi

    service:
      postgresql:
        controller: postgresql
        ports:
          postgresql:
            port: 5432

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: nfs
        accessMode: ReadWriteMany
        size: 5Gi
        globalMounts:
          - path: /var/lib/postgresql/data