---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      redis:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/redis
              tag: 7.4-alpine
            args: ["redis-server", "--save", "60", "1000"]
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi

    service:
      redis:
        controller: redis
        ports:
          redis:
            port: 6379

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /data