apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  generation: 2
  name: helm-info
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: podinfo
    - kind: HelmChart
      name: default-podinfo
    - kind: HelmRelease
      name: podinfo
      namespace: default
