---
# Longhorn replicated storage with backup capabilities
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-backup
  annotations:
    longhorn.io/description: "Single replica storage with automatic backups"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
---
# Longhorn single replica for CI/CD artifacts
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-fast
  annotations:
    longhorn.io/description: "Single replica for fast, non-critical storage"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "strict-local"