---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./default
  - ./flux-system
  - ./homepage
  - ./kube-system
  - ./longhorn-system
  - ./media
  - ./network
  - ./observability
  - ./slack-alerts
  - ./storage