apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:64uI+YNK8olEbicPS4TDTg7D89KS470+gMGca4FirV4=,iv:ppgLhjIg2Gix/f+thvyKz/HcMDU6PnsahODhOxNnNCU=,tag:lRtIhiURxvc34RxRVG+m4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lcg2c8efnnnmmlq5ftp85v8enwc7adhrm4auqnjfckww76fj6vrs5redm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaW9qcytUMXJ1SzAwcXRl
            OVVCVU5nVVI4ZG9iZ1RJMmxGL2dSb1pmUW5JCnZCNUNkZUZIT0xuZ3czWXBrUU50
            THJVOEE3T282QWtYVzJ4U1BrMjdlREEKLS0tIHdJT2lub3YyRy9vVHFYbmJJaDdI
            L25KbUZ3eTVyeDdpOXpvbEkxV21yaTQKxlmHZ6cpXmmZxyNNm1Uvch8+MkTfy88b
            vhYFFwwjL3IfnvkG9OlX8SHCtl6ZumVTwwfNDNVLTemsn7QCcBXafw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T17:24:50Z"
    mac: ENC[AES256_GCM,data:uhkF+3rjNlkVNwYXFvRVuo6WIkgE5iUUhQlO8VNYGjxdAi//q+Ch1wrjUO+Zyv4QkZJQodlKYQrB6MMDMgR4sQT47L/lqGmg+xn5MphdvRYb+e8PRtXWxLkGsPxmfam89g5YqQJzpAnaA8tdxiv2u3IoAhJollxZLx9CEFKFrhQ=,iv:WSof15Dnaf+7KEuxkITt9ofIE/z04fFk3gJL1GJiwY0=,tag:ipxvHh1Ki81iGwJy/8nnww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
